#[path = "08/eight.rs"]
pub mod eight;
#[path = "05/five.rs"]
pub mod five;
#[path = "04/four.rs"]
pub mod four;
#[path = "09/nine.rs"]
pub mod nine;
#[path = "01/one.rs"]
pub mod one;
#[path = "07/seven.rs"]
pub mod seven;
#[path = "06/six.rs"]
pub mod six;
#[path = "10/ten.rs"]
pub mod ten;
#[path = "03/three.rs"]
pub mod three;
#[path = "02/two.rs"]
pub mod two;
#[path = "11/eleven.rs"]
pub mod eleven;
