[package]
name = "advent2021"
version = "0.1.0"
authors = ["Brett Spradling <brett@spradling.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0.48"
env_logger = "0.9.0"
nom = "7.1.0"
tokio = { version = "1.14.0", features=["macros"] }
itertools = "0.10.3"
