#[path = "days/08/eight.rs"]
pub mod eight;
#[path = "days/11/eleven.rs"]
pub mod eleven;
#[path = "days/05/five.rs"]
pub mod five;
#[path = "days/04/four.rs"]
pub mod four;
#[path = "days/09/nine.rs"]
pub mod nine;
#[path = "days/01/one.rs"]
pub mod one;
#[path = "days/07/seven.rs"]
pub mod seven;
#[path = "days/06/six.rs"]
pub mod six;
#[path = "days/10/ten.rs"]
pub mod ten;
#[path = "days/03/three.rs"]
pub mod three;
#[path = "days/02/three"]
pub mod two;
