#[path = "days/05/five.rs"]
pub mod five;
#[path = "days/04/four.rs"]
pub mod four;
#[path = "days/01/one.rs"]
pub mod one;
#[path = "days/03/three.rs"]
pub mod three;
#[path = "days/02/two.rs"]
pub mod two;
